### ISSUE TITLE
[Feat] FE to BE: /auth/check API가 필요합니다

### ISSUE THREAD

**Issue by chichoon** [boostcampwm-2022/web25-SCOPA#22]
## 💁 설명

- 로그인 로직을 (아까 상의했던 대로) 로그인 페이지에 종속적이지 않게, 미들웨어처럼 다른 페이지에서도 상위에서 돌아가는 컴포넌트로 분리했습니다
- 이때 사용하는 API가 `/auth/check` 라서 최대한 빨리 구현되면 좋을 것 같습니다아아아아아
- 프론트엔드에서는 쿠키만을 사용하여 GET 요청을 보내고, 서버에서 유저 id 와 username 을 내려주거나 통신 코드를 반환해주면 됩니다 ([기술 기획서](https://github.com/boostcampwm-2022/web25-SCOPA/wiki/%EA%B8%B0%EC%88%A0-%EA%B8%B0%ED%9A%8D%EC%84%9C#authcheck) 참고)

## 📑 체크리스트

> 구현해야하는 이슈 체크리스트

- [x] /auth/check API 구현

## 🚧 주의 사항

> 이슈를 구현할 때 유의깊게 살펴볼 사항

- `id` (고유값 - Primary Key로 쓰이는 그 숫자값, string), `username` (사용자가 지은 유저명, string) 두 개를 보내주시면 됩니다 (상단 링크의 기술 기획서 참고)
- GET 요청입니다 (클라이언트에서 쿠키 외에 별도의 정보를 보내지 않습니다!!!)
- 프론트엔드에서 보내는 쿠키를 검증하고 파싱해서 유저 정보를 보내주면 됩니다
- 쿠키를 내려주실 땐 `secure httpOnly` 쿠키로 내려주세요 (xss 공격 방지)
- 이번 주 내로 주시면 좋습니다 (빠르면 3일 내)

**Comment by chichoon** [comment]
사실 id (primary key로 이용되는 그 값) 으로만 로그인 체크를 할 거라서 (id가 null이면 로그인되어있지 않은 것으로 판단)
username에 무슨 값이 오든 지금까지는 크게 상관없습니다
username이나 이메일이 필요한 곳은 상세정보 페이지랑 마이페이지 정도뿐이라...
id만 제대로 (문자열 형식, '17499138' 이런식으로) 들어오면 괜찮습니다

**Comment by Min-h-96** [comment]
아 그러면 일단 id 값만 보내는 걸로 하겠습니다.
