### ISSUE TITLE
[Feat] FE to BE : id의 유효성 처리 API가 필요합니다.

### ISSUE THREAD

**Issue by HSeo-git** [boostcampwm-2022/web25-SCOPA#24]
## 💁 설명

- 회원가입화면에서 id 중복확인 기능이 있습니다.
- 이에 대해서, 중복확인을 포함한 id 유효성 검사 API 구현을 부탁드립니다.

## 📑 체크리스트

> 구현해야하는 이슈 체크리스트

- [ ] "/auth/validate?id=ABC" 형식으로 id는 쿼리스트링으로 보낼 예정
- [ ] db에서 id 중복성 체크
- [ ] id 자체의 유효성 검사(4글자 이상 15글자 이하, 알파벳과 숫자로만 이루어진 아이디 등)
- [ ] 성공/실패에 대한 응답은 아래와 같으나(Wiki 기술기획서 참고), 이에 대해서는 논의가 필요하오니 하기의 주의사항 부분을 읽어주시길 부탁드립니다.
```
성공 시 
res.status(200).send({
  code: 200,
  message: '유효한 ID'
});

실패 시
res.status(400).send({
  code: 400,
  message: '유효하지 않은 ID'
});
```
## 🚧 주의 사항

> 이슈를 구현할 때 유의깊게 살펴볼 사항

- 현재, 성공 실패는 위와 같이 유효성에 대해 200/400코드로만 응답하고 있고 실패 메시지도 하나 밖에 없습니다. 실패할 시에 어떤 이유로 실패했는지(중복, 유효성 조건 미적합 등)에 대해 상세히 안내해주시면 프론트에서 사용자에게 보다 나은 안내가 가능할 것 같습니다.
- id 자체의 유효성 조건에 대해서는 논의가 필요하시다면 요청하여 주시고 보편적인 기준(특정 글자 수 이상, 문자열 요소 구성 등)을 도입하신다면, 알려주신다면 프론트에서도 사용자에게 별도 안내를 할 수 있도록 하겠습니다.

**Comment by chichoon** [comment]
주의사항에 덧붙이자면 기술기획서에 적힌 성공시 / 실패시 전송되는 데이터 (에러코드 `400`, `유효하지 않은 ID` 등) 은 어디까지나 예제이고 실제로는 에러코드나 메시지같은 건 자유롭게 편집해서 보내주심 됩니다 @Min-h-96 @dohyeon-han
